# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    configs:
        my_config_1:
            toolbar: "my_toolbar_1"
            uiColor: "#000000"
    toolbars:
        configs:
            my_toolbar_1: [ "@tool" ]
        items:
            tool: [ 'Styles', 'Format', 'FontSize','Maximize' ]

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

