controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

auth:
    path: /login
    controller: App\Controller\UserController::index

register:
    path: /register
    controller: App\Controller\RegisterController::index

home_page:
    path: /home
    controller: App\Controller\MainPageController::index

redirToMain:
    path: /
    controller: App\Controller\MainPageController::redirectToMain

delete_image:
    path: /image/delete/{id}
    controller: App\Controller\ImageController::delete
delete_fav_genre:
    path: /genre/delete/{id}
    controller: App\Controller\FavouriteGenresController::delete
avatar:
    path: /image/avatar/{imageId}/{profileId}
    controller: App\Controller\ImageController::avatar

exit:
    path: /exit
    controller: App\Controller\ExitController::index

profile:
    path: /profile
    controller: App\Controller\ProfileController::index

profile_get:
    path: /profile/{id}
    controller: App\Controller\ProfileController::getProfile

search:
    path: /search
    controller: App\Controller\SearchController::index
search_by_genre:
    path: /searchBy/{id}
    controller: App\Controller\SearchController::search
like:
    path: /like/{id}
    controller: App\Controller\LikeController::index
like_delete:
    path: /like/delete/{id}
    controller: App\Controller\LikeController::delete